print("No python existem forma literais pra escrever números\n")
print("1      #int\n")
print("2.0    # float\n")
print("3.     # float\n")
print("4+5j   # complex\n")
print("números tipo integer (int)")
print("1,2,3,4,5,6...10,11,12\n")
print("números tipo float (float)")
print("1., 2., 3. ou podendo ser escrito dessa forma 4.0, 5.2, 6.9...10.0\n")
print("números tipo complex (complex)")
print("1+5j\n")
